### ISSUE TITLE
download doesn't work on firefox 36

### ISSUE THREAD

**Issue by felix9** [AndrewNeo/faextender#32]
Symptom: it creates an .faextmp file but it remains zero bytes, and re-attempt triggers "file already exists".

Cause: mozilla added yet another parameter to nsIWebBrowserPersist.saveURI, breaking compatibility in an awkward way.
http://hg.mozilla.org/mozilla-central/diff/4a7db36c3c75/embedding/components/webbrowserpersist/nsIWebBrowserPersist.idl

**Comment by gaiaweylyn** [comment]
I noticed this a while ago. When Firefox nightly moved to v36 the same thing happened. Then I moved back to beta, which was v35 at the time, and it fixed the problem. 

Now that beta has moved to v36 its broken again.
Downgraded to Regular Firefox v35, fixed.

I am now almost certain there's simply something in v36 that breaks the extension. 

I can safely bet that when the official regular release of Firefox makes it to v36, it will break again.

I am aware you do not support beta/nightlies, but I would thouroughly reccomend you look into this.

**Comment by gaiaweylyn** [comment]
Well there it is, I didn't look at the code, but I figured as much.

**Comment by FallenWolf** [comment]
The Firefox release channel recently (yesterday) updated to v.36 and thus broke the download-function of faextender completely (as already described here). 

Has anyone found a fix to this yet? I'm going to look into this (or at least try to do so), but unfortunately I've got other time-sensitive stuff to worry about at the moment :(
For everyone who also wants to downgrade to Firefox.v.35.0.1 in the meantime - downloads are available here: ftp://ftp.mozilla.org/pub/firefox/releases/35.0.1/win32/

The update to Firefox.v.36 didn't only break faextender, it also broke other extensions as well (e.g. "CookieSafe")...

Might be helpful: https://blog.mozilla.org/addons/2015/01/13/compatibility-for-firefox-36/

**Comment by felix9** [comment]
iirc it's a one-line fix. I can extract the diff when I get home tonight if needed.

**Comment by FallenWolf** [comment]
Would be much appreciated if you could do so :)

**Comment by felix9** [comment]
https://github.com/AndrewNeo/faextender/pull/34

**Comment by AndrewNeo** [comment]
Fixed by #34
