### ISSUE TITLE
Won't download anything with the new site's skin

### ISSUE THREAD

**Issue by Galio99** [AndrewNeo/faextender#35]
I'm sure we should wait till the new skin passes from beta to an official version; just letting you guys know, the function of pressing "f" to add to favorites still works, but the button of "download now" is nowhere to be seen, nor the "s" key to save pictures. everything is working fine on the previous skin. Thank you guys, you do an awesome work! :D

**Comment by AndrewNeo** [comment]
Not supporting the beta skin due to sudden and unannounced changes.
