### ISSUE TITLE
FA Site update screwed up faextender - even when using the "classic" template

### ISSUE THREAD

**Issue by FallenWolf** [AndrewNeo/faextender#36]
Unfortunately FA added a sidebar to the submission-view on the right of the image and thus breaking faextender.

Maybe we should also add an option to revert back to the old "submission view" style in addition to restoring the main functionality of faextender?

Edit1:
https://www.furaffinity.net/journal/6689390
There's already an "remove the sidebar"-uproar going on in the comments of that journal. If they decide to revert back to the old style remains to be seen.

Edit2:
Nope, looks like that ugly sidebar is here to stay:
https://www.furaffinity.net/journal/6689390#cid:45474876
"Sidebar was a necessary addition.
It will be populated with a mini gallery preview and maybe other things in the near future to make it more useful. "

**Comment by Kadah** [comment]
Knowing them, the sidebar will either change again in the next few days or it'll be several weeks. Might want to wait a day on fixing it, I'm sure IMVU is pushing for the sidebar ad to go live again.

Most likely what broke this was the normalizing of the header between the beta template and the live one.

**Comment by AndrewNeo** [comment]
Fixed with 615b27cba

**Comment by Kadah** [comment]
Can confirm fixed, thanks :+1:
