### ISSUE TITLE
FA added folders / changed stuff and broke FAExtender

### ISSUE THREAD

**Issue by FallenWolf** [AndrewNeo/faextender#38]
Seems like FA changed some stuff again, mainly adding gallery-folders which in turn breaks FAExtender.

Stuff that's broken:
- Gallery "open everything in tabs" (while "New Submissions" still works fine)
- Submission file download stuff including hotkey-functions

**Comment by DaMoot** [comment]
Can confirm this as well. FA did a bunch of unannounced changes.

**Comment by Kadah** [comment]
Its no longer unannounced, some of it does seem nice. Any changes to the layouts usually just break the xpath expressions used to find things on the pages.

**Comment by FallenWolf** [comment]
Changelog for all FA-related changes is here:
https://changelogs.furaffinity.net/wiki/Site_Changelog
