### ISSUE TITLE
FAE functionality still broken after update

### ISSUE THREAD

**Issue by DaMoot** [AndrewNeo/faextender#39]
Following the update FAE functionality is still broken. No options anywhere on submissions are being displayed.

Attempted removing the addin completely and reinstalling without luck. No download button, Open Artist Folder, and no notification that the file still exists.

Confirmed on two computers.

**Comment by TomTheDragon** [comment]
Same problem for me.

**Comment by Kitsoran** [comment]
It was broken for me till a short while ago, once I dismissed the site announcement bar for the journal I got the [Download] button back on submissions. I can reproduce by going incognito in Waterfox (an unofficial 64-bit Fx build).

**Comment by tokar86a** [comment]
I have the same problem to. all the buttons have disappeared.

**Comment by DaMoot** [comment]
Confirmed what KItsoran said is correct. Dismissed the announcement bar and functionality is restored.

**Comment by Galio99** [comment]
I can confirm that once you dismiss the site announcement it works again <3
