### ISSUE TITLE
Broken under Firefox 48?

### ISSUE THREAD

**Issue by tERB00** [AndrewNeo/faextender#43]
After Firefox update extension stopped working. It is enabled, I can open settings tab, but there is no buttons on Furaffinity website.

Does anybody else have the same issue or is it only me? If so how can you debug extension?

**Comment by krizzap** [comment]
I have had this issue for quite a while, it simply doesn't work anymore. I'm pretty sure this project is long since abandoned, the last update was almost a year ago. Terrible shame.

**Comment by TomTheDragon** [comment]
I am using v48.0.2 and it still works without any problems for me.

**Comment by AndrewNeo** [comment]
Working for me. Are you using the FA beta? Are you on a release track version of Firefox?

**Comment by tERB00** [comment]
I'm on FF 49.0.1 release. FA Classic template.

**Comment by AndrewNeo** [comment]
Can you post the output of the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) when loading a page? I can't reproduce any issue.

**Comment by tERB00** [comment]
Now it's working back up again. Straaaange...
